modLoader="javafml"
loaderVersion="[1,)"
license="OSL-3.0"
issueTrackerURL="${issue_url}"

[[mods]]
modId="zume"
version="${mod_version}"
displayName="${mod_name}"
displayURL="${mod_url}"
logoFile="icon.png"
authors="${nolij}"
description="""
${mod_description}
"""

[[dependencies.zume]]
modId="minecraft"
type="required"
mandatory=true
versionRange="${forge_minecraft_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.zume]]
modId="embeddiumplus"
type="optional"
mandatory=false
versionRange="[1.2.6,)"
ordering="BEFORE"
side="CLIENT"
