modLoader="javafml"
loaderVersion="[1,)"
license="OSL-3.0"
issueTrackerURL="${issue_url}"

[[mods]]
modId="zume"
version="${mod_version}"
displayName="${mod_name}"
displayURL="${mod_url}"
logoFile="icon_large.png"
authors="${nolij}"
description="""
${mod_description}
"""

[[dependencies.zume]]
modId="minecraft"
type="required"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="CLIENT"
