name: ci
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Adjust Gradle permission
        run: chmod +x ./gradlew
      - name: Build mod
        run: ./gradlew build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: primitive-zume
          path: "**/primitive-zume-*.jar"
