name: build
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Packages
        run: sudo apt-get install -y advancecomp
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - name: :build
        run: ./gradlew build --stacktrace
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zume
          path: |
            **/zume-*.jar
            **/*mappings.txt
