name: build
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Packages
        run: sudo apt-get install -y advancecomp
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: 'gradle'
          cache-dependency-path: |
            **/.gradle/
            **/build/
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - name: :build
        run: ./gradlew build --stacktrace --no-daemon
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: zume
          path: |
            **/zume-*.jar
            **/*mappings.txt
